apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-database-deployment
spec:
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
        - name: auth-database-deployment
          image: postgres:16
          ports:
            - containerPort: 5632
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: auth-database-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: auth-database-secrets
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: database
                  name: auth-database-secrets