apiVersion: v1
kind: Service
metadata:
  name: category-database-service
spec:
  selector:
    app: category-db
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30433
  type: NodePort
