apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/category/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi