apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-redis-sentinel
spec:
  selector:
    matchLabels:
      app: redis
      role: sentinel
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
        tier: backend
    spec:
      containers:
        - name: category-cache-sentinel
          image: bitnami/redis-sentinel
          env:
            - name: REDIS_MASTER_HOST
              value: category-redis-master

          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379

