apiVersion: v1
kind: Service
metadata:
  name: category-redis-sentinel
  labels:
    app: redis
    role: sentinel
    tier: backend
spec:
  ports:
    - port: 26379
      targetPort: 26379
      nodePort: 30381
  selector:
    app: redis
    role: sentinel
    tier: backend
  type: NodePort