apiVersion: v1
kind: Service
metadata:
  name: product-redis-slave
  labels:
    app: redis
    role: replica
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30401
  selector:
    app: redis
    role: replica
    tier: backend
  type: NodePort