apiVersion: v1
kind: Service
metadata:
  name: category-redis-slave
  labels:
    app: redis
    role: replica
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30380
  selector:
    app: redis
    role: replica
    tier: backend
  type: NodePort