apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: replica
      tier: backend
  replicas: 2
  template:
      metadata:
        labels:
          app: redis
          role: replica
          tier: backend
      spec:
        containers:
          - name: category-cache-slave
            image: redis
            command:
              - "redis-server"
            args:
              - '--slaveof'
              - category-redis-master
              - '6379'
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            env:

              - name: REDIS_HOST
                value: category-cache-master
            ports:
              - containerPort: 6379
