apiVersion: v1
kind: Service
metadata:
  name: product-redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30400
  selector:
    app: redis
    role: master
    tier: backend
  type: NodePort