apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-pod
          image: endienasg/foxshop-auth:main
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: auth-secrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db-name
                  name: auth-secrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: auth-secrets
            - name: SR_JWT_PRIVATE
              valueFrom:
                secretKeyRef:
                  key: sr-jwt-private
                  name: auth-secret-api-keys
            - name: SR_JWT_PUBLIC
              valueFrom:
                secretKeyRef:
                  key: sr-jwt-public
                  name: auth-secret-api-keys
            - name: SR_ACCESS_EXP_HOURS
              valueFrom:
                secretKeyRef:
                  key: access-expired-hours
                  name: auth-secrets
            - name: SR_ACCESS_EXP_MINS
              valueFrom:
                secretKeyRef:
                  key: access-expired-minutes
                  name: auth-secrets
            - name: SR_REFRESH_EXP_DAYS
              valueFrom:
                secretKeyRef:
                  key: refresh-expired-days
                  name: auth-secrets
            - name: SR_ZONE_ID
              valueFrom:
                secretKeyRef:
                  key: sr-zone-id
                  name: auth-secrets