apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-pod
          image: endienasg/foxshop-auth:main
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: auth-secrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db-name
                  name: auth-secrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: auth-secrets
            - name: SR_JWT
              valueFrom:
                secretKeyRef:
                  key: sr-jwt
                  name: auth-secrets