apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth-deployment
          image: endienasg/foxshop-auth
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: auth-secrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db-name
                  name: auth-secrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: auth-secrets
