apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product-pod
          image: endienasg/foxshop-product:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: product-database-secrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: product-database-secrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: product-database-secrets
            - name: JWT_SC_P
              valueFrom:
                secretKeyRef:
                  key: secret_public
                  name: product-secrets
            - name: JWT_EXP_ZONE
              valueFrom:
                secretKeyRef:
                  key: exp_zone
                  name: product-secrets