apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-deployment
spec:
  selector:
    matchLabels:
      app: category
  replicas: 1
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category-pod
          image: endienasg/foxshop-category:main
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: category-database-secrets
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: database
                  name: category-database-secrets
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: category-database-secrets
            - name: JWT_SC_P
              valueFrom:
                secretKeyRef:
                  key: secret_public
                  name: category-secrets
            - name: JWT_EXP_ZONE
              valueFrom:
                secretKeyRef:
                  key: exp_zone
                  name: category-secrets